name: Build Laravel Base Image - Slim Version

on:
  push:
    paths:
      - ".github/workflows/laravel-image-slim.yml"
  workflow_run:
    workflows: ["Build Laravel Base Image"]
    types:
      - completed

jobs:
  slim:
    name: Slim
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ghcr.io/${{ github.repository }}/laravel:main
          tag: "slim"

      - run: echo "${REPORT}"
        env:
          REPORT: ${{ steps.slim.outputs.report }}

      - run: docker image push "${{ github.repository }}" --all-tags
