name: Build Laravel Base Image

on:
  push:
    paths:
      - "laravel/**"
      - ".github/workflows/laravel-image.yml"

jobs:
  cd:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/laravel
          flavor: |
            latest=false
          tags: |
            type=sha
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:laravel"
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Slim it!
      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ghcr.io/${{ github.repository }}/laravel
          tag: "slim"

      # Dump the report
      - run: echo "${REPORT}"
        env:
          REPORT: ${{ steps.slim.outputs.report }}

      # Push to the registry
      - run: docker image push "${{ github.repository }}" --all-tags
